name: bnm_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  after_layout: ^1.2.0
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.2.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.0
  get_it: ^8.2.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  
  #// from khuygaa
  audioplayers: ^6.5.0
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  google_fonts: ^6.3.0
  hexcolor: ^3.0.1
  page_transition: ^2.2.1
  readmore: ^3.0.0
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.2
  youtube_player_flutter: ^9.1.2
  dio: ^5.9.0
  blurrycontainer: ^2.1.0
  flutter_secure_storage: ^9.2.4
  form_builder_validators: ^11.2.0
  pull_to_refresh: ^2.0.0
  flutter_widget_from_html: ^0.17.1
  #//



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ios_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/images/
     - assets/images/thumbnails/
     - assets/images/events/
     - assets/svg/
     - assets/icon/
     - assets/model/

  